import { boolean, literal, union, object, string, InferInput, optional } from 'valibot'

export const partnerFormSchema = object({
	insurer: object({
		mode: union([literal('new'), literal('select'), literal('skip')]),
		cnpj: optional(string()),
		name: optional(string()),
		insurerId: optional(string()),
		selectedLabel: optional(string()),
		insurerCnpj: optional(string()),
		status: optional(string()),
		createdAt: optional(string()),
		suspendedAt: optional(string()),
		cancelledAt: optional(string()),
		reactivatedAt: optional(string()),
	}),
	channel: object({
		enabled: boolean(),
		useCurrentInsurer: union([literal('yes'), literal('no')]),
		cnpj: optional(string()),
		name: optional(string()),
		insurerId: optional(string()),
		insurerCnpj: optional(string()),
		linkedInsurerName: optional(string()),
		linkedInsurerId: optional(string()),
		status: optional(string()),
		createdAt: optional(string()),
		suspendedAt: optional(string()),
		cancelledAt: optional(string()),
		reactivatedAt: optional(string()),
	}),
	product: object({
		enabled: boolean(),
		useCurrentChannel: union([literal('yes'), literal('no')]),
		name: optional(string()),
		channelId: optional(string()),
		channelCnpj: optional(string()),
		linkedChannelName: optional(string()),
		linkedChannelId: optional(string()),
		status: optional(string()),
		createdAt: optional(string()),
		suspendedAt: optional(string()),
		cancelledAt: optional(string()),
		reactivatedAt: optional(string()),
		dfiFile: optional(string()),
		acceptanceModel: union([literal('simplificado'), literal('completo')]),
		ageMin: optional(string()),
		ageMax: optional(string()),
		maxTerm: optional(string()),
		dfiEnabled: union([literal('yes'), literal('no')]),
		dfiValue: optional(string()),
		mipValue: optional(string()),
		examsStandard: optional(string()),
		examsAdditionalMale: boolean(),
		examsAdditionalFemale: boolean(),
		examsAdditionalMaleAge: optional(string()),
		examsAdditionalFemaleAge: optional(string()),
		propertyResidential: boolean(),
		propertyCommercial: boolean(),
		propertyMixed: boolean(),
	}),
})

export type PartnerFormValues = InferInput<typeof partnerFormSchema>

export const defaultPartnerFormValues: PartnerFormValues = {
		insurer: {
			mode: 'new',
			cnpj: '',
			name: '',
			insurerId: '',
			selectedLabel: '',
			insurerCnpj: '',
			status: '',
			createdAt: '',
			suspendedAt: '',
			cancelledAt: '',
			reactivatedAt: '',
	},
	channel: {
		enabled: true,
		useCurrentInsurer: 'yes',
		cnpj: '',
		name: '',
		insurerId: '',
		insurerCnpj: '',
		linkedInsurerName: '',
		linkedInsurerId: '',
		status: '',
		createdAt: '',
		suspendedAt: '',
		cancelledAt: '',
		reactivatedAt: '',
	},
	product: {
		enabled: true,
		useCurrentChannel: 'yes',
		name: '',
		channelId: '',
		channelCnpj: '',
		linkedChannelName: '',
		linkedChannelId: '',
		status: '',
		createdAt: '',
		suspendedAt: '',
		cancelledAt: '',
		reactivatedAt: '',
		dfiFile: '',
	acceptanceModel: 'simplificado',
		ageMin: '',
		ageMax: '',
		maxTerm: '',
		dfiEnabled: 'no',
		dfiValue: '',
		mipValue: '',
		examsStandard: '',
		examsAdditionalMale: false,
		examsAdditionalFemale: false,
		examsAdditionalMaleAge: '',
		examsAdditionalFemaleAge: '',
		propertyResidential: false,
		propertyCommercial: false,
		propertyMixed: false,
	},
}
